### ISSUE TITLE
repeat signal every N days 

### ISSUE THREAD

**Issue by eXense-auth** [you-apps/ClockYou#111]
### Describe your suggested feature

there is no possibility to set the alarm day and no possibility to set it to repeat every N days.

for example set date 20.02.2023 and repeat it every 4 days

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by M00NJ** [comment]
You can set the day by tapping on the expand icon in the alarm card and selecting the day you want the alarm to go off. Let's say you work on Tue and Fri, select "T" and "F". Now to the second part. I don't really see the point here. I've never heard that somebody goes to work every three days. I've also never seen a clock app that supports it. Are you looking for a reminder? This is a feature you usually see in a task app like Tasks by Google. This can be a useful feature, but not in a clock app in my opinion. Therefore I would close this as not planned.
