### ISSUE TITLE
Persistent timers

### ISSUE THREAD

**Issue by M00NJ** [you-apps/ClockYou#119]
### Describe your suggested feature

Timers are deleted when they expire or the app is closed. If you use a specific timer very often, let's in a workout, having to set a new timer every time will get annoying quickly. It also defeats the purpose of adding a label to the timer. It would be nice, if the timers are saved. Or at least the ones that where labeled. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The timers would need to be stored in the app's database, similar to how we currently store alarms.

**Comment by M00NJ** [comment]
Fair enough :) I will try to implement this, however this is above of what I can do currently. I still need to get my Kotlin fundamentals down. Databases is something I haven't look at yet, so this might take some time...
