### ISSUE TITLE
World Clock should have the country name, not the continent name.

### ISSUE THREAD

**Issue by SuhasDissa** [you-apps/ClockYou#122]
### Describe your suggested feature

As a person with basically zero geographic knowledge, I find it pretty difficult to find the correct world clock with the current layout. It only has the city names and the continent names.

For example if I wanna know the current time in Germany, the obvious thing to do is to search for "germany" in the search box. but that gives no results.

| Clock You | Samsung Clock |
|---------------|------------------------|
| <img src="https://github.com/you-apps/ClockYou/assets/64766434/78809d1f-63bf-4e87-ba0e-539230070b34" > | <img src="https://github.com/you-apps/ClockYou/assets/64766434/16dadfd1-0385-4fc6-958d-f3d4871ee122"> |

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It seems like that's not possible with the `TimeZone` system API unfortunately, as it only provides the continent and region/city.

**Comment by Bnyro** [comment]
So we could either use a library or hardcode the time zones in the app, based on a list of time zones in the internet.

**Comment by SuhasDissa** [comment]
The GNOME clock is using this for timezone data.
https://github.com/GNOME/libgweather/blob/main/data/Locations.xml
