### ISSUE TITLE
alarms on first page

### ISSUE THREAD

**Issue by fusionneur** [you-apps/ClockYou#128]
### Describe your suggested feature

I want alarms to be first page instead of clock which is quite visible on any phone. Would be nice to have a setting to allow this

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by M00NJ** [comment]
I made this default, since setting an alarm is the most commonly used function and all all other clock apps I used (GClock, AOSP Clock) do this as well.

**Comment by Bnyro** [comment]
True, agreed.
