### ISSUE TITLE
Timer numpad doesn't work after switching to minimal picker

### ISSUE THREAD

**Issue by Zumux** [you-apps/ClockYou#135]
### Steps to reproduce

1. Turn "Use minimal timer duration picker" on
2. Try to set a timer

### Expected behavior

Be able to set a timer normally 

### Actual behavior

Only able to enter one number

### Clock You version

6.0

### Android version

Android 13

### Other details

It seems to work properly after the app is completely closed and reopened 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by M00NJ** [comment]
Can you send a screen recording of this happening?
