### ISSUE TITLE
The design of the settings is broken in some localizations

### ISSUE THREAD

**Issue by Artem13327** [you-apps/ClockYou#149]
### Clock You version

6.0

### Android version

12.1

### Other details

![IMG](https://github.com/you-apps/ClockYou/assets/68551925/99be7d3f-5a82-4c6c-bdc1-1b13a6fc5d27)
![IMG](https://github.com/you-apps/ClockYou/assets/68551925/17ac4354-cbf0-4474-a2a5-6afca6bc5dd6)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by M00NJ** [comment]
The issue is caused by the translation text being to long. This setting will be changed in the near future and the translation along side it, which will hopefully fix this issue as well.
