### ISSUE TITLE
Disable an alarm once 

### ISSUE THREAD

**Issue by TalOrenshtein** [you-apps/ClockYou#158]
### Describe your suggested feature

Imagine you have an alarm for the weekday, and you don't need it for a specific day, when you try to disable the alarm, a pop menu will appear and the user will choose between
1. Turn the alarm off once. (//meaning that it'll work when the next weekday comes)
2. Disable the alarm.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by NeuroException** [comment]
I didn't want to open another issue for my request, because it is very similar to this one. A "Dismiss" button on an alarm would be very useful for when, for example, you woke up earlier than your alarm.

**Comment by julianfairfax** [comment]
> I didn't want to open another issue for my request, because it is very similar to this one. A "Dismiss" button on an alarm would be very useful for when, for example, you woke up earlier than your alarm.

To add to this, a notification should be sent telling you an alarm is coming and offering a dismiss option. Like the stock clock does.

**Comment by Bnyro** [comment]
Closing in favor of #151
