### ISSUE TITLE
Increasing alarm volume

### ISSUE THREAD

**Issue by bartlibert** [you-apps/ClockYou#162]
### Describe your suggested feature

I would like to have an "increasing alarm volume" settings (and maybe something similar for timers). This means the alarm would start out at a low volume, but get increasingly louder when it's not dismissed within a certain time (e.g. 10 seconds).
This is very useful if you have a baby sleeping in your room, but still want to wake up on time ;)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
We use notifications for playing the alarm sounds. These do not allow us to set the volume, hence we can't implement that unfortunately.
