### ISSUE TITLE
Seconds still shown after disabling

### ISSUE THREAD

**Issue by Mennaruuk** [you-apps/ClockYou#164]
### Steps to reproduce

1. Go to settings
2. Disable "Show seconds"
3. Return to the Clock tab

### Expected behavior

Seconds should be omitted.

### Actual behavior

Seconds appear even when disabled.

### Clock You version

6.1

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please share a recording.

**Comment by Mennaruuk** [comment]
https://github.com/you-apps/ClockYou/assets/52135169/f92c6ff0-0447-40a6-9ce3-f0cdb5e55747

**Comment by SuhasDissa** [comment]
This bug only occurs in 12 Hour clock

[This](https://github.com/you-apps/ClockYou/blob/26c24c5c23c2926bd696a176efb1bdc19596c235/app/src/main/java/com/bnyro/clock/util/TimeHelper.kt#L44C65-L44C75) Regex doesn't work when having AM or PM at the end of the time string

```kotlin
if (!showSeconds) formattedTime = formattedTime.replace(":\\d{2}$".toRegex(), "")
```

**Comment by SuhasDissa** [comment]
We can use this

![image](https://github.com/you-apps/ClockYou/assets/64766434/9a7a6dc4-2bcd-4a0f-8aff-49e016bd13e9)

Instead of

![image](https://github.com/you-apps/ClockYou/assets/64766434/96383e34-7792-46f1-bb26-93d3cc21ee01)

**Comment by Bnyro** [comment]
Oh right, that makes sense! I missed the "AM" in the recording.

The proposed solution looks like a good idea :+1:
