### ISSUE TITLE
Power off alarm permission?

### ISSUE THREAD

**Issue by xfzv** [you-apps/ClockYou#173]
### Describe your suggested feature

It would be nice if the app could use the power off alarm permission, like [qw123wh/new-clock](https://github.com/qw123wh/new-clock/blob/6b0fa7da9e1ce9518c523a3f44a99eaeb4d9117f/app/src/main/java/com/best/deskclock/DeskClock.java#L75) for example :

![1](https://github.com/you-apps/ClockYou/assets/78810647/f7aa3b56-40c5-46f5-85a1-73510c9c3919)

Unless I'm mistaken, it currently does not.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not supported by Android natively, hence I don't aim to add it.
