### ISSUE TITLE
Unresponsive stopwatch notification

### ISSUE THREAD

**Issue by NeuroException** [you-apps/ClockYou#179]
### Steps to reproduce

1. Open the latest ClockYou release
2. Go to the stopwatch section
3. Start the stopwatch
4. Close the app

### Expected behavior

The stopwatch should react to the button presses of the notification. Dismissing the notification should kill the background process.

### Actual behavior

You will now find a notification of the stopwatch, which is unresponsive. It does not react to clicking the "stop" or "pause" button. Even if you dismiss the notification, the background process will still continue to run.

### Clock You version

0.6.2

### Android version

Android 13 / GrapheneOS

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by CT-66** [comment]
I've noticed the stopwatch notification displays options to stop and resume even after a stopwatch has been reset.
