### ISSUE TITLE
Ability to disable the (default) main time zone

### ISSUE THREAD

**Issue by serrq** [you-apps/ClockYou#18]
I would like to see only the tabs managed by me. 

Personally I don’t need the main clock because I set a tab with my country's time zone.

![1000006687](https://user-images.githubusercontent.com/113377431/230790671-cea186a1-6470-4cee-bde2-810878ba5b39.jpg)

**Comment by Bnyro** [comment]
Thanks for the suggestion, however I currently don't have any plans to allow such minor tweaks.
