### ISSUE TITLE
Various UI Suggestions

### ISSUE THREAD

**Issue by NeuroException** [you-apps/ClockYou#187]
### Describe your suggested feature

# Timer
Only show the FAB's if the timer value is above zero. Additionally, they should be more visible.
I would suggest to use secondary and tertiary color to make them stand out a bit more. Maybe even size differences between them.
Right now, they kinda visually blend in with the numpad.
![Screenshot_20231007-093401](https://github.com/you-apps/ClockYou/assets/118199015/3a2b6acd-bb8a-43a0-b747-2c53e3175df1)

- Increase the size of this FAB. Theres a lot of empty space.
- I would place the Close icon also in a circular shape, but with a red background.
![Screenshot_20231007-095754](https://github.com/you-apps/ClockYou/assets/118199015/775c29a3-bcf2-4f0d-bcfb-6caaa67c46e0)

- Place the timer quick selection above the numpad. Optionally in a vertically scrollable container, so that it only takes up one row and doesn't blend into the FAB's.
- Decrease their button sizes. They are quite bulky. Maybe even use a pill shape for them. (Could look good, but i'm not sure right now).
![Screenshot_20231007-100307](https://github.com/you-apps/ClockYou/assets/118199015/fa95dcdf-d2df-45aa-bed6-c7579dda3b95)

# Alarm
- Make the alarm time's font a bit bolder.
- The label telling you in how much hours it will ring, is slightly shifted to the right.
- Increase FAB size, change shape into circle, place it in center, like in the stopwatch section.
- Change icon from a pen into a plus. This is more convinient, because this fab does not edit something, rather than adding something.

![Screenshot_20231007-094534](https://github.com/you-apps/ClockYou/assets/118199015/abbe1287-45fc-4fc0-965d-746b9891ab8a)

### Other details

This is not everyones taste, but a slide transition between these sections would look awesome. This fade transition is not as fancy as the rest of the app.

Everything is up to you guys, as always, these are suggestions. You are doing awesome work.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SuhasDissa** [comment]
#189
