### ISSUE TITLE
"00" button broken

### ISSUE THREAD

**Issue by daBroma** [you-apps/ClockYou#201]
### Steps to reproduce

1. Enable number pad for timer in the settings
2. Enter a number in the timer
3. Click on the 00 button

### Expected behavior

Well "00" should be inputted not "0". 

### Actual behavior

"0" happens instead of "00"

### Clock You version

6.2

### Android version

Android 13,  2023 October patch

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SuhasDissa** [comment]
already fixed ec4ca90
