### ISSUE TITLE
Keep Screen On, on timers

### ISSUE THREAD

**Issue by chromer030** [you-apps/ClockYou#206]
### Describe your suggested feature

Option to keep screen on when timer is going on...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by VishnuSanal** [comment]
hi, i would like to work on this issue
