### ISSUE TITLE
Full screen alarm not working on Android 14

### ISSUE THREAD

**Issue by basings** [you-apps/ClockYou#207]
### Steps to reproduce

1. Set an alarm
2. Turn off screen and wait for alarm to ring
3. The alarm sound plays, but there is no full screen alarm

To turn of the alarm the device has to be unlocked and the alarm notification needs to be tapped. Dismissing the notification by swiping makes it impossible to turn off the alarm and the app needs to be force quit.

### Expected behavior

Full screen notification should be displayed

### Actual behavior

No full screen notification displayed

### Clock You version

6.3

### Android version

Grapheneos A14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by M00NJ** [comment]
You can no longer turn off alarms by dismissing the notofication. You need to tap in the notification and then tap in dismiss. But there are some improvements to be made here.

**Comment by SuhasDissa** [comment]
This will only show a notification if you are already using the device. And if you keep the phone screen off, it will show a full screen alert like every other alarm app.

**Comment by M00NJ** [comment]
I can reproduce this then. I only get the full screen alarm when tapping on the notification. Full screen notification permission is given. Maybe it's related to GrapheneOS.

**Comment by SuhasDissa** [comment]
> I can reproduce this then. I only get the full screen alarm when tapping on the notification. Full screen notification permission is given. Maybe it's related to GrapheneOS.

The full screen alarm worked fine on A14 emulator, A13 physical device (Samsung) and A11 tablet (Samsung)

**Comment by M00NJ** [comment]
That's strange. Then it might really be GOS. I could ask in the matrix chat if anyone has experienced this and what OS they're on. Also I would rename this issue to something like "Full screen alarm not working on some devices" since the current title and description are not true afaik.

**Comment by basings** [comment]
I can confirm that the fullscreen alarm appears when tapping on the notification. It does not automatically appear when the screen is locked.
In the case you dismiss the notification (swipe it away), there's no way to stop the alarm. That's apparently what happened when I opened the issue.

**Comment by M00NJ** [comment]
Yes, same thing happened to me. When you dismiss the notification by swiping there's no way to turn off the alarm. You'll have to force quit the app. It definitely woke me up though...

**Comment by SuhasDissa** [comment]
https://9to5google.com/2023/04/14/android-14-full-screen-notifications/

Maybe this is the problem

**Comment by M00NJ** [comment]
Could be. But this should affect all android 14 devices then. I'll ask around now...

**Comment by SuhasDissa** [comment]
No, It gives the user the option to turn them off. They are enabled by default.

**Comment by SuhasDissa** [comment]
Maybe they are turned off by default in GrapheneOS?

**Comment by basings** [comment]
Full screen for clock you is enabled on my device

**Comment by M00NJ** [comment]
> Maybe they are turned off by default in GrapheneOS?

No, I checked and they're on

**Comment by M00NJ** [comment]
@matchboxbanasynergy has kindly tested this on stock Android 14 and confirmed the issue in the matrix group chat. I will update the title accordingly. I wonder why it didn't show up in emulator.

**Comment by SuhasDissa** [comment]
https://source.android.com/docs/core/permissions/fsi-limits
