### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [you-apps/ClockYou#208]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/5538977142#L614

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/82b95e4f72a21cd0ab002ab966c7d9815a3c44ab

Will diff locally , brb

**Comment by licaon-kter** [comment]
diff log: [clo12.log](https://github.com/you-apps/VibeYou/files/13364489/clo12.log)

CI APK: https://gitlab.com/fdroid/fdroiddata/-/jobs/5538977142/artifacts/file/tmp/com.bnyro.clock_12.apk

Not sure why stuff is moved around :(

**Comment by M00NJ** [comment]
I'll have a look at the log when I get home. I can't think of a reason for this though. I handled the release for ClockYou the same way as ConnectYou and that one seems fine. Also for VibeYou I only did the release notes, Bnyro handled the rest. While I might make a mistake due to inexperience, I don't think he did. So I'm confused here.

**Comment by licaon-kter** [comment]
I'm rebuilding the other apps right now, I doubt they are ok :(

**Comment by licaon-kter** [comment]
And the results are in, `wallpaper`, `translate`, `recorder` and `contacts` built fine locally... makes me wonder... brb

**Comment by licaon-kter** [comment]
I had to rebuild Clock and Vibe locally, just to make sure, but indeed they still fail

**Comment by Bnyro** [comment]
I've rebuilt the apk now and the diff seems to be okay now:
```
❯ zipcmp app-release.apk com.bnyro.clock_12.apk 
--- app-release.apk
+++ com.bnyro.clock_12.apk
- file 'META-INF/CERT.RSA', size 1057, crc d9fc03b9
- file 'META-INF/CERT.SF', size 86641, crc d2ca9928
- file 'META-INF/MANIFEST.MF', size 86567, crc aa37538
```

Not sure why the previous build has such a diff...

**Comment by licaon-kter** [comment]
Thanks https://gitlab.com/fdroid/fdroiddata/-/commit/e38dc54b8a703ae574245999fb42f7f11dfa5e6c
