### ISSUE TITLE
not requesting Alarms and Reminders permission Android 14

### ISSUE THREAD

**Issue by heckarman** [you-apps/ClockYou#209]
### Steps to reproduce

1. Install the app
2. Set an alarm

### Expected behavior

It should shout on time.

### Actual behavior

The app crashes unless `Alarms and Reminders` permission is granted. It should either ask the user for that permission or as usual, it should grant that permission by itself.

Major issue is that it never makes any sound but rather only vibrates. Even after manually changing default tone, it never made any sound.

### Clock You version

6.3

### Android version

Android 14 

### Other details

GrapheneOS 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by quinb96** [comment]
I have this same issue. The alarm has never worked for me.

**Comment by SuhasDissa** [comment]
Try increasing the system alarm volume

**Comment by heckarman** [comment]
That did solve the issue. Wait. Why the app pushes sound in media channel? Alarms have their own specific Alarms channel AFAIK.

**Comment by SuhasDissa** [comment]
- This app should ask for Alarm permission. 
- This uses the alarm sounds channel to play alarms and It should respect the alarm volume settings. (I tested this on android 14 emulator and it worked fine)

**Comment by SuhasDissa** [comment]
https://github.com/you-apps/ClockYou/assets/64766434/4889069c-2cc6-482f-804a-fda470c95a26

**Comment by heckarman** [comment]
Yes, looks like latest version fixed it. My bad.
