### ISSUE TITLE
Alarms use notification audio instead of alarm audio

### ISSUE THREAD

**Issue by Bitwolfies** [you-apps/ClockYou#212]
### Steps to reproduce

It should use alarm audio. Not notification audio.

### Expected behavior

Uses alarm audio 

### Actual behavior

Uses notification audio

### Clock You version

6.2

### Android version

14

### Other details

When actually testing alarm sounds in app, it uses the proper alarm sound volume. When actually firing off it uses the notification audio, which I have silenced, making the app pointless.

The app clearly *can* use the alarm audio. Like I said it uses it when you preview a sound. It just doesn't use it where it counts.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SuhasDissa** [comment]
What device are you using?

**Comment by SuhasDissa** [comment]
This issue should be fixed in Clock You version 6.3
