### ISSUE TITLE
Alarm doesn't ring on vibrate

### ISSUE THREAD

**Issue by kzhe2059** [you-apps/ClockYou#213]
### Steps to reproduce

1. Set phone on vibrate
2. Set alarm
3. Wait for alarm

### Expected behavior

On all other clock apps, there is a ringing sound even on vibrate

### Actual behavior

Clock vibrates but does not ring

### Clock You version

6.2 (11)

### Android version

Android 13

### Other details

I love this app and would love to use it but this stops me from using it/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SuhasDissa** [comment]
Use the latest version (6.3)

**Comment by kzhe2059** [comment]
I will try this but the latest version is not on F-Droid yet so that is why I was not on it

**Comment by Bnyro** [comment]
You have to grant the notifications permission.

**Comment by M00NJ** [comment]
I don't know about older Android versions, but on A14 alarm and notification volume are handled separately . If I put my phone on vibrate, nothing changes for ClockYou, because vibrate only mutes calls and notifications not alarms.

**Comment by SuhasDissa** [comment]
> I don't know about older Android versions, but on A14 alarm and notification volume are handled separately . If I put my phone on vibrate, nothing changes for ClockYou, because vibrate only mutes calls and notifications not alarms.

He's using the v6.2 and this version plays the alarm tone through the notification audio channel. Only the versions 6.3 and above use the alarm channel

**Comment by M00NJ** [comment]
> Only the versions 6.3 and above use the alarm channel

I see. That's a nice change 👍

**Comment by kzhe2059** [comment]
Yeah 6.3 fixed, thanks
