### ISSUE TITLE
Show how many hours each timezone is behind or ahead

### ISSUE THREAD

**Issue by SuhasDissa** [you-apps/ClockYou#214]
There is one killer feature that I noticed in Xiaomi and Samsung apps:
It's that I can see how many hours each timezone is **behind** or **ahead** my timezone:

![photo_5393236317179072238_y](https://github.com/you-apps/ClockYou/assets/100644/fcc743ec-2f48-4591-b49d-8249e692ce8f)

_Originally posted by @soshial in https://github.com/you-apps/ClockYou/issues/163#issuecomment-1817891549_

**Comment by soshial** [comment]
Also, the time format should [follow the 12/24-hour format](https://stackoverflow.com/a/59401660/231590) setting, that user sets in Android. Thank you
