### ISSUE TITLE
Alarm even device is powered off

### ISSUE THREAD

**Issue by heckarman** [you-apps/ClockYou#219]
### Describe your suggested feature

AFAIK, this does not require system level permissions.
You can look at stock clock app (com.android.clock) provided by LineageOS. 

### Other details

Allows the device to ring ala even when the device is powered off

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SuhasDissa** [comment]
Android doesn't support this out of the box. This is not possible without using a custom boot loader and a custom kernel.

**Comment by heckarman** [comment]
I tried digging in a bit and found this: 
https://stackoverflow.com/questions/12233623/alarmmanager-when-the-phone-is-turned-off-android

The reason behind this feature request is that on LineageOS alarm clock it was a feature. I've that installed on my other phone that runs Pixel Experience to see if that works without additional permissions..

And I'm not sure whether `org.codeaurora.POWER_OFF_ALARM` requires system level privileges of that's true then that's a dead end.
![codeaurora](https://github.com/you-apps/ClockYou/assets/147484873/87755c09-933b-4093-bef7-f15c938f2c52)
