### ISSUE TITLE
Just a Question

### ISSUE THREAD

**Issue by Samyak-Bumb** [you-apps/ClockYou#226]
### Describe your suggested feature

Hey just wanted to ask you which resources you used to learn kotlin & which videos will you refer to watch

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You can ask such questions here: https://matrix.to/#/#you-apps:matrix.org.

I myself mostly used the official Android developer documentations sometimes, but I've learned the most from working on open source projects, even when I started working with Kotlin. I already had some minor programming experience before that however. I can NOT recommend using YouTube tutorials to learn Android development, as long as you don't try things yourself you will keep forgetting it.

**Comment by M00NJ** [comment]
Here's the free, official course for Kotlin and Jetpack Compose: https://developer.android.com/courses/android-basics-compose/course In this course you'll learn everything you need to know to create an app like ClockYou.
