### ISSUE TITLE
Choosing sound effect for the timer plays the sound infinitely 

### ISSUE THREAD

**Issue by dgudim** [you-apps/ClockYou#230]
### Steps to reproduce

Add a new timer
Click on the bell icon
Choose different sounds
Close the dialog/app

### Expected behavior

The sound should only play for 2-3 seconds and should also stop when the dialog is closed or another sound is played

### Actual behavior

The sound never stops and clicking on several just plays them together 

### Clock You version

6.4

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by dgudim** [comment]
https://github.com/you-apps/ClockYou/assets/34401005/1421bf38-efeb-4e67-b2df-4be48d211b09

This is how it sounds

**Comment by asl97** [comment]
A thing I notice is that while the timer service is running, even when swiping the app close, the sound continue playing.

only when no timer is running and thus no timer service (visible as icon on status bar), then swiping the app close would stop the sounds.

[Record_2023-12-20-20-41-45.webm](https://github.com/you-apps/ClockYou/assets/4752645/e36e40d2-5701-4801-bdfc-b0e059f9d361)
