### ISSUE TITLE
Alarm does not go off when all week days are deselected

### ISSUE THREAD

**Issue by eandersons** [you-apps/ClockYou#241]
### Steps to reproduce

1. Create a new alarm and set time.
2. Deselect all week days.
3. Wait for the set time to come.

### Expected behavior

Alarm fires and then turns itself off.

### Actual behavior

There are indications about alarm at system level in quick settings menu and clock widget, but when the time comes, nothing happens.

### Clock You version

6.4 (13)

### Android version

Android 8.1

### Other details

When I deselected all week days I expected to create an one-time alarm that would turn itself off when it is dismissed, but instead I got an alarm that is always on and never goes off.

If an alarm not firing when all week days are deselected is the intended behaviour (which is logical, but without any additional visual clues also confusing), then the user experience could be improved by one of the following:

- dimming the alarm or showing an alert that the alarm will not go off;
- automatically turning off the alarm, and all week days or the next one would be re-enabled when turning it back on;
- implementing any other solution that makes it obvious that an alarm will not go off at the set time if all week days are deselected.

#236 hopefully will fix the one-time alarm part of this issue, but the silent repeating alarm when all week days are deselected most probably would still be present but it would be an issue with a lesser significance.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
I'm not of your opinion:
If you a user disabled all days, it should be self-explaining for everyone that the alarm won't fire. And since we have one-time alarms now as a new feature, I don't think any further changes are necessary here.
