### ISSUE TITLE
Number pad for alarms.

### ISSUE THREAD

**Issue by TheTidark390** [you-apps/ClockYou#254]
### Describe your suggested feature

Could work something like the existing google clock app, where you select the time by typing the hour and the minute in 2 separate boxes right next to each other.

For example :
[08] [30]

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SuhasDissa** [comment]
Is there a specific reason for requesting this feature?

**Comment by TheTidark390** [comment]
> Is there a specific reason for requesting this feature?

I am trying to find replacements to google apps, and as of today this app is the only one that really is great, I got really used to that system, and also find it way simpler, as instead of scrolling trought a time wheel thing you can just type it.

I have found that almost no app does this and find myself in others apps always taking 2x more time  to setup something as basic as a alarm (or even events for calendar apps).
