### ISSUE TITLE
Alarm timer doesn't show days left

### ISSUE THREAD

**Issue by PlayerXYT** [you-apps/ClockYou#255]
### Steps to reproduce

1. Create an alarm set in a minute
2. Make the only day of the week the next day (Monday for this example)

### Expected behavior

The countdown subtitle should say "1 day 1 minute", "1 day" or "Mondays"

### Actual behavior

The countdown says "1 minute"

### Clock You version

6.4 (f-droid)

### Android version

13

### Other details

The alarm correctly doesn't sound, this is only to do with the countdown display

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SuhasDissa** [comment]
This is already fixed
