### ISSUE TITLE
A notification like an a hour before alarm time

### ISSUE THREAD

**Issue by b-RAYO** [you-apps/ClockYou#260]
### Describe your suggested feature

It would be nice if there was an alarm notification with dismiss button an hour before the alarm went off

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Thanks for the suggestions, however there are currently no plans for implementing such a feature.
