### ISSUE TITLE
batch alarm maker

### ISSUE THREAD

**Issue by 4rtemis-4rrow** [you-apps/ClockYou#261]
### Describe your suggested feature

here's how I think it could work

it would need 3 inputs from the user, start time, end time, and interval, and it would simply set alarms between the start time and end time, with the specified interval, it'd be nice if it also can set things like repetition 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Personally I feel like this is something that should rather be done using a calendar / reminder app, opinions @SuhasDissa and @M00NJ ?

Etar (calendar app) for example does support such recurring events with an alarm/notification when the event time arrived.

**Comment by M00NJ** [comment]
I agree with Bnyro. I don't think a basic clock app needs this. Sounds like an interval timer for workouts to me. I'm sure there a projects like this around.

**Comment by 4rtemis-4rrow** [comment]
lol I am a very heavy sleeper

I have 30 alarms, 1 every 2 minutes, the alarm sound is a damn nuke siren

that's kinda the main reason I suggested batch alarms

anyways, now that you mention it, I think you're right
