### ISSUE TITLE
Deleting an alarm changes which alarms are active

### ISSUE THREAD

**Issue by discerno** [you-apps/ClockYou#264]
### Steps to reproduce

1. Create three alarms, e.g. 10:00, 11:00, 12:00.
2. Enable only the second alarm (11:00).
3. Delete the first alarm (10:00).

### Expected behavior

The alarm at 11:00 remains enabled, the alarm at 12:00 remains disabled.

### Actual behavior

The alarm at 12:00 is enabled instead, and the alarm at 11:00 is disabled.

### Clock You version

6.4

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SuhasDissa** [comment]
This is only a visual glitch. It doesn't actually enable/disable the alarms.
You can switch the tab and come back to it to temporarily fix the glitch.

Nevertheless, we'll try our best to get this fixed ASAP.
