### ISSUE TITLE
Alarm snoozing is not working

### ISSUE THREAD

**Issue by eandersons** [you-apps/ClockYou#271]
### Steps to reproduce

1. Add a new alarm, set it to go off after a few minutes and to snooze for a few minutes.
2. Wait for alarm to ring.
3. Press the button "Snooze".
4. Wait the configured snooze time.

### Expected behavior

Alarm goes off again after the configured snooze time.

### Actual behavior

Nothing happens.

### Clock You version

7.0 (14)

### Android version

Android 8.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SuhasDissa** [comment]
It would be helpful if you could tell us what the configured snooze time is

**Comment by eandersons** [comment]
It seems that the snooze time does not matter - I tried 1, 2, 5 minutes.

Another detail I did not mention previously is that this misbehaviour was observed with one-time alarms. I did not check if the same happens also with repeated alarms.

**Comment by siSSSou** [comment]
Same problem with version 7.1 on lineageos 18.1.
Snooze turns alarm off !
(Alarm is set as one-time alarm)

**Comment by gosheffect** [comment]
I have the same issue on Android 14 GrapheneOS on version 7.1 (15)
