### ISSUE TITLE
Gradual volume increase in alarms

### ISSUE THREAD

**Issue by m0yP** [you-apps/ClockYou#273]
### Describe your suggested feature

App is awesome but it's kinda annoying to wake so sudden.

### Other details

A slider or setting in seconds would be great.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Gamer750** [comment]
I would also like to see this
