### ISSUE TITLE
Timezone names make user think capitals are wrong

### ISSUE THREAD

**Issue by soshial** [you-apps/ClockYou#285]
### Steps to reproduce

Try to add Slovenian or Slovakian timezone.

### Expected behavior

Timezones should show correct capitals.
Capital of Slovenia is Ljubljana, capital of Slovakia is Bratislava.

### Actual behavior

![photo_5341497470389180890_y](https://github.com/you-apps/ClockYou/assets/100644/7b84b61c-50b4-4d7f-b179-15b10a9f05e7)

### Clock You version

7.1

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The listed cities are not tge capital but representive cities for the country.

**Comment by soshial** [comment]
@Bnyro:

Wait but Belgrade is **not even located in Slovenia**! I would expect that if I search a country in timezone list -- I will at least see cities located in the country.
