### ISSUE TITLE
Optimize the UI for smaller screens

### ISSUE THREAD

**Issue by serrq** [you-apps/ClockYou#286]
OnePlus CPH2399
Android 13
CY 7.1 (15)

![1000105933](https://github.com/you-apps/ClockYou/assets/113377431/e9932e3a-b155-47b1-b31d-e11009a724be)

![1000105936](https://github.com/you-apps/ClockYou/assets/113377431/0ea96b21-c228-4fad-8c78-a7db5f92779b)

**Comment by M00NJ** [comment]
I gave this some thought. Here are some possible solutions:

1. Screenshot: Bring back the default time picker
2. Screenshot and #300 : Using the official `Segmented Button` might fix this. It was added to Compose [recently](https://material.io/blog/material-3-compose-1-2)
3. Screenshot: This is the big one. There are multiple issues with this screen and also the number pad. I think the best solution here is to drop the example timers and save timers like we do with alarms. Imo it makes more sense this way and it's also how GClock and the AOSP clock do it. The `label` feature would also make more sense if the timers persists. Atm you can name a timer, but that name is gone when the timer runs out, which makes it kinda useless. The idea is that the timer tab launches you in the timer list first. There you can start saved timers, delete them with `swipe-to-dismiss` and create new ones with the FAB, which then brings you to the time picker / number pad. This would avoid many of the spacing / overlapping components issues and make the time picker screen much cleaner.

I recently created a bunch of [mock-ups.](https://github.com/M00NJ/material-you-mockups/tree/main/Clock) They cover these ideas as well.

**Comment by SuhasDissa** [comment]
One temporary fix for the `3` will be moving the save button to the top app bar, as an action button.
