### ISSUE TITLE
Better Alarm and Alarmdroid Features from Netzpurist/Smart Software

### ISSUE THREAD

**Issue by Revan335** [you-apps/ClockYou#287]
### Describe your suggested feature

Hello,

I would like it was added Features from Netzpurist/Smart Software Apps, Better Alarm and Alarmdroid.

For example:
Color Labels for the Timer
Hints for Cancel Timer like Math Operations, click Numbers, ...
Time, Weather, ... Speaking through Timer
Change next running time or skip Timers
Individual Timers like Song, Song+Hint, other Volume or Vibration, ....
Calendar Style

Sad, that are Better Alarm no longer available on the Website or Store and Alarmdroid Update Years old.

He is the Webpage from the Developer: https://netzpurist.de/

And here a Picture
![1707395535035](https://github.com/you-apps/ClockYou/assets/18167280/6d3d0feb-63de-433f-8ed8-fe4e4f082042)

The apk, I can upload, when this allowed.

Many Thanks!

Greetings

Revan335

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Sorry, we don't plan to add such advanced features, this would additionally be more code to maintain and I think the audience for such features is not given here.
