### ISSUE TITLE
Backup Function

### ISSUE THREAD

**Issue by Revan335** [you-apps/ClockYou#288]
### Describe your suggested feature

Hello,

Backup Function was great for Backup here Timers, Settings, .... for Device Migration ...

Many Thanks

Greetings

Revan335

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not planned because the data contained by the app is only very simple and thus easy to restore manually.
