### ISSUE TITLE
Broken timer/ goes into negative digits.

### ISSUE THREAD

**Issue by spidikot** [you-apps/ClockYou#290]
### Steps to reproduce

1. Start any timer.
2. Close the app.
3. Wait until the time runs out.

### Expected behavior

Some kind of notification with a sound should appear, notifying the user that the time of specific timer ran out of time.

### Actual behavior

Once any timer gets to 00:00 time left, 
![Screenshot_2024-02-11-06-37-18-684](https://github.com/you-apps/ClockYou/assets/115490436/bfeee68d-fcf7-4b63-916f-13c139ac3fff)
it just goes into negative digits, and keeps going on for hours until you manually close the timer notificatin. Also, if you set a timer in the app, don't close it, and just wait until time runs out, the app will just crash, still, with no notification.

### Clock You version

7.1

### Android version

Android 12

### Other details

Just in case, Im sure that my volume is NOT muted, or something like that. The default anroid flock, and other clock apps dont have the same issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SuhasDissa** [comment]
This happens when the app crashes while the timer is running, causing the notification to get stranded.

**Comment by SuhasDissa** [comment]
#252
