### ISSUE TITLE
Option to vibrate for timers

### ISSUE THREAD

**Issue by name-tar-xz** [you-apps/ClockYou#294]
### Describe your suggested feature

An option to enable vibration for timers either globaly or per timer like it is for alarms

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
It might be worth considering enabling vibration by default without an option for it I think? Users can still disable vibration for that specific notification type in Android's notification settings for Clock You. Opinions @SuhasDissa and @M00NJ ?

**Comment by SuhasDissa** [comment]
I've been thinking of using a full screen notification for timers and play sounds within a service (similar to alarms).
Using notifications to play continuous sounds is less than ideal.

**Comment by M00NJ** [comment]
> It might be worth considering enabling vibration by default without an option for it I think? Users can still disable vibration for that specific notification type in Android's notification settings for Clock You. 

That's a valid approach imo

**Comment by M00NJ** [comment]
> I've been thinking of using a full screen notification for timers and play sounds within a service (similar to alarms). 

Also a good idea 👍

**Comment by Bnyro** [comment]
> I've been thinking of using a full screen notification for timers and play sounds within a service (similar to alarms). Using notifications to play continuous sounds is less than ideal.
>
I personally think that this is way too much overkill for timers, I'd prefer to keep things simple, clean and intuitive to use, without adding much additional code.
