### ISSUE TITLE
When the alarm starts, the screen stays off

### ISSUE THREAD

**Issue by alr86** [you-apps/ClockYou#304]
### Describe

If the screen is off and the alarm time comes, the phone screen will remain off and only the alarm sound will be played. If I turn on the phone, the normal lock screen will open and I must click on the alarm notification twice to open the alarm screen.

### Expected behavior

Open alarm screen to turn it off

### Actual behavior

Nothing, just play alarm sound.

### Clock You version

7.1 (15)

### Android version

14

### Other details

I am on CrDroid custom rom without google apps

**Comment by TechFanTheo** [comment]
I have the same issue on stock android (Samsung One UI). It seem to affect almost all FOSS clock apps. This basically make it an useless alarm. The only app I found is https://github.com/yuriykulikov/AlarmClock, but it's only an alarm. Maybe Clock YouYou could incorporate some of it's code?

**Comment by SuhasDissa** [comment]
Make sure you have Full screen alerts enabled in settings.
goto **Settings > Apps > Special Access > Full screen alerts**

<img src="https://github.com/you-apps/ClockYou/assets/64766434/0cc7e0a6-1dba-4098-97de-c39d6da1b4cf" width="30%">

**Comment by alr86** [comment]
> Make sure you have Full screen alerts enabled in settings. goto **Settings > Apps > Special Access > Full screen alerts**
> 
> <img alt="" width="30%" src="https://private-user-images.githubusercontent.com/64766434/325157091-0cc7e0a6-1dba-4098-97de-c39d6da1b4cf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMDIyMTcsIm5iZiI6MTcxNDMwMTkxNywicGF0aCI6Ii82NDc2NjQzNC8zMjUxNTcwOTEtMGNjN2UwYTYtMWRiYS00MDk4LTk3ZGUtYzM5ZDZkYTFiNGNmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDEwNTgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0MDJkZDM3YWY3MjJhMjhjYzk5ZDc2MzU0MzhhYThiNjUzMGI2MjgzMDIxNGE5YTA1NzMzZDAxNDYzODQ3MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4BBjq9Ob7CtTprk9f6W0AttlpNxK9yH9a-PqVl5Zqp4">

That was my problem, thank you❤️

**Comment by I-I-IT** [comment]
Still doesn't work.

**Comment by alr86** [comment]
This issue was closed, open a new one with refrence to here
