### ISSUE TITLE
Vertical clock 3 x 2 widget

### ISSUE THREAD

**Issue by Zafrkant** [you-apps/ClockYou#306]
### Describe your suggested feature

Hello,

I would like to thank developers for great contribution to the community.

I would like to kindly ask if you can change widget size for vertical clock widget to be 3 x 2, because 3 x 3 takes to many space on home screen, and from 3 x 2 is can be resized at will, like on Google Clock.

Thank you in advance.

Best Regards, zfk

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Can you please test the builds from the bottom [here](https://github.com/you-apps/ClockYou/actions/runs/8038989640)? I think https://github.com/you-apps/ClockYou/pull/181 should have already addressed that?

**Comment by Zafrkant** [comment]
Hi Bnyro,

I have checked, everything works fine.

Thanks.
