### ISSUE TITLE
alarms all set for regular time even though today is dst and phonr clock correctly made the switch

### ISSUE THREAD

**Issue by zombiehoffa** [you-apps/ClockYou#307]
### Steps to reproduce

All my alarms think it is stabdard time when it switched to dst last night. If i add a new alarm it is also on standard time instead of dst. This should switxh with the system clock

### Expected behavior

Alarmss adjuat to dst

### Actual behavior

Alarms stay on standard tine

### Clock You version

7.1 (15)

### Android version

14

### Other details

Grapheneos latedt

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ggtylerr** [comment]
Nearly missed work due to this :/ But yes, all the alarms are still tied to non DST.
![Screenshot_20240310-093847.png](https://github.com/you-apps/ClockYou/assets/28498877/3da876e2-3a85-4afa-b391-9c0c3815113f)

**Comment by Imrealybored** [comment]
I've noticed that the time is correct from 12:00 a.m. - 1:59 a.m., but it jumps and hour (for the time remaining until the alarm) once you try setting it past 2:00 a.m.
