### ISSUE TITLE
More snooze options, snooze button long press ?

### ISSUE THREAD

**Issue by shodanx2** [you-apps/ClockYou#312]
### Describe your suggested feature

I would like to dynamically change my snooze duration sometimes

The current 10 minute is fine most of the time. 
Sometimes I would like 15 minutes
Sometimes I need 30 minutes

I think, with long press of the snooze button, these options could be added without cluttering up the user interface !

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SuhasDissa** [comment]
The option is already there

<img src="https://github.com/you-apps/ClockYou/assets/64766434/0f76a7c8-62ad-4c11-a3b3-e5f4aa06d775" width="30%">

**Comment by shodanx2** [comment]
I mean, from the "alarm ringing" screen.

By "dynamically change" I mean, while the alarm is ringing and without interacting too much with the phone and other screens. 
When you're hitting snooze, you're still in dream land and trying to stay there.

Most of the time, I prefer to snooze 10 minutes.

But sometimes, I know I have 30 minutes of snooze, I would like to get that solid 30 min but still get up in 30.

That's why I was thinking maybe you just longpress the snooze. Maybe it pops a "snooze 20 min , 30 min" button, you move your finger on the extra time you want and let go.

**Comment by shodanx2** [comment]
I look forward to trying this !
