### ISSUE TITLE
 add UTC to the clock list

### ISSUE THREAD

**Issue by e075e** [you-apps/ClockYou#316]
### Describe your suggested feature

UTC should be in the list alongside the cities, so the user can add it

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Out of scope.

**Comment by AF0BL** [comment]
Is this still out of scope? I have just switched from android to grapheneOS, this app worked great for my day one timer needs, but now I need to compare several timezones including UTC. Omitting UTC is an unusual choice
