### ISSUE TITLE
clock wrongly report "same time"

### ISSUE THREAD

**Issue by e075e** [you-apps/ClockYou#317]
### Steps to reproduce

My android timezone is Rome (IT)

1. Clock tab
2. add Rome + Casablanca

### Expected behavior

Times are

Casablanca 09:04 one hour behind
Rome 10:04 same time

### Actual behavior

Now 10:04
Casablanca 09:04 **same time**
Rome 10:04 same time

"same time" is wrongly stated in Casablanca

![Imagepipe_0](https://github.com/you-apps/ClockYou/assets/15078341/1c6e42a5-cc2e-4465-ad29-2e93ccf562db)

### Clock You version

7.1

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SuhasDissa** [comment]
#283
