### ISSUE TITLE
Widgets use a too large font, making time unreadable 

### ISSUE THREAD

**Issue by edwinst** [you-apps/ClockYou#318]
### Steps to reproduce

1. Install Clock You
2. Add digital 3x1 or 3x2 widget to home screen.

### Expected behavior

I expect the widget to display the time well inside the bounding box of the widget.

### Actual behavior

Time display is too large and is clipped (see screenshot).
![Screenshot_2024-03-21-23-04-20-456_com miui home](https://github.com/you-apps/ClockYou/assets/2489158/1f0b318a-3e41-4b3a-8aa1-c2d4b20fbcd3)

### Clock You version

7.1 (15)

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/you-apps/ClockYou/pull/181
