### ISSUE TITLE
Avoid overlap of timer save/play buttons with quick selects

### ISSUE THREAD

**Issue by edwinst** [you-apps/ClockYou#319]
### Describe your suggested feature

The timer UI with the keypad is great and one of the main reasons I want to use this app. A small annoyance is that the "save" button partially overlaps the right-most quick select button(s). See screenshot:
![Screenshot_2024-03-22-09-00-15-702_com bnyro clock-edit](https://github.com/you-apps/ClockYou/assets/2489158/1fc038b3-688c-4ccd-b678-e9a02f4d65f0)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Floating action buttons always overlap the main content, that's how they're designed in Material 3. You can still read the text, so that's out of scope.
