### ISSUE TITLE
Skipped alarms still show up as next alarm in Home Assistant

### ISSUE THREAD

**Issue by Manu3l0us** [you-apps/ClockYou#320]
### Steps to reproduce

This is a bit of a difficult one to describe and I don't know wether it is an issue with the HA companion app or with Clock You. 

I use the Home Assistant companion app to report the next active alarm to my Home Assistant server so that e.g. my espresso machine is heated up when I get up in the morning. When using Clock You instead of Google Clock or AlarmDroid, an alarm that is skipped (because it only runs on weekdays for example) will still show up on Home Assistant as the next Alarm for the current day.

### Expected behavior

Skipped alarms should not show up for the current day as next alarm.

### Actual behavior

Skipped alarms should not show up for the current day as next alarm.

### Clock You version

7.1

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SuhasDissa** [comment]
#302

**Comment by Manu3l0us** [comment]
@SuhasDissa Thank you, #302 is indeed the same issue in the end. I haven't identified it when looking for it.
