### ISSUE TITLE
Digital Click widget without date

### ISSUE THREAD

**Issue by limbusdev** [you-apps/ClockYou#321]
### Describe your suggested feature

Provide a digital clock widget without date or give settings for the existing widgets to disable date.

### Other details

#68 seems to be somewhat related but states the opposite, which seems to be wrong.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
But what's the point about not having the date? Is there any disadvantage of seeing the date?

**Comment by limbusdev** [comment]
If I have another widget with the date, I don't want it twice. Like some calender widget.
