### ISSUE TITLE
alarm goes off at wrong time (24 hr system error)

### ISSUE THREAD

**Issue by itsmmt305** [you-apps/ClockYou#33]
### Steps to reproduce

set an alarm for any time

### Expected behavior

it should ring at the set time.. according to 24 hr system

### Actual behavior

any alarm before 12:00 (pm) rang at T±12 hr (e.g 06:00 tomorrow morning alarm rang at 18:00 this evening)
any alarm after 12:00 pm doesnt ring
explains why my 14:20 alarm didnt go off

![Screenshot_2023-04-12-18-00-56-842_com miui home](https://user-images.githubusercontent.com/94820934/231463003-d8b4289d-98dc-441c-a2f7-46260acff440.jpg)

![Screenshot_2023-04-12-18-01-12-658_com bnyro clock](https://user-images.githubusercontent.com/94820934/231463026-aa587c73-6f0e-4875-a9e4-87038e6021bd.jpg)

### Clock You version

v2.1

### Android version

Android 12 / MIUI 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by mxwmnn** [comment]
Can confirm! 

Even aware of it if I set the alarm to the time it doesn't ring and skips it to the next day. So the alarm isn't working.

**Comment by PranavPurwar** [comment]
for me when i set alarm to 06:00, it instead fired the alarm on 18:00

**Comment by junkminerman** [comment]
I am not having alarms ring at all :(

**Comment by junkminerman** [comment]
I am now having alarms play with a 12 hour delay after a reboot. What's more, alarms seem to go off at the right time if i turn on the alarm between 0-12 (only tested between 0-1). Not sure if this helps though

**Comment by eclairevoyant** [comment]
@junkminerman This was already mentioned in the reported issue, no need to duplicate info in comments.

**Comment by junkminerman** [comment]
@eclairevoyant I'm not sure it was. I'm trying to say that if I turn my alarm on between 0-12 an alarm set to 8:00 will actually go off at 8:00 rather than 20:00

**Comment by any1th3r3** [comment]
FWIW, I have noticed that alarms do go off at the correct set time if I have another clock app installed alongside Clock You and alarms setup in said app and Clock You, regardless of whenever I turn them on, eg:
- Phone set to 24hr
- Clock You alarm set at 06:00
- Other clock app alarm set at 06:10 (eg [Simple Clock](https://github.com/SimpleMobileTools/Simple-Clock))
Both alarms will go off at the correct time.  
However, if I only have Clock You installed, the alarm will go off at 18:00 (and will show up as such in my phone's quick settings pull-down notification).

**Comment by itsmmt305** [comment]
so you mean to say clock you is in the sucker fish mode right now.

**Comment by BioRider17** [comment]
After some experimenting, I think the issue revolves around the AM/PM toggle. Is it possible those 2 are swapped?

**Comment by ViktorKahu** [comment]
Any update on this?

How high of a priority is this?

IMHO, alarms are 99% of the reason to have an otherwise largely unneeded clock app, and if they don't work properly...

**Comment by Bnyro** [comment]
It's a high priority, but I don't have a clue what's causing it.

**Comment by itsmmt305** [comment]
> It's a high priority, but I don't have a clue what's causing it.

dont stress about it.. i'm sure you'll find a way around it. ✨🫂

**Comment by Titaniumtown** [comment]
Can reproduce, almost messed up my morning schedule.

**Comment by Neon-44** [comment]
> FWIW, I have noticed that alarms do go off at the correct set time if I have another clock app installed alongside Clock You and alarms setup in said app and Clock You, regardless of whenever I turn them on, eg:
> - Phone set to 24hr
> - Clock You alarm set at 06:00
> - Other clock app alarm set at 06:10 (eg [Simple Clock](https://github.com/SimpleMobileTools/Simple-Clock))  
>   
> Both alarms will go off at the correct time.  
> However, if I only have Clock You installed, the alarm will go off at 18:00 (and will show up as such in my phone's quick settings pull-down notification).

Cannot reproduce. Alarms are always offset by 12 hrs, regardless of what i do in simple-clock.

**Comment by Neon-44** [comment]
after some quick research myself i think i may have found the Problem.

The problem seems to be that you're using Calendar.HOUR when you should be using Calendar.HOUR_OF_DAY for scheduling an Alarm.

https://stackoverflow.com/questions/42745481/alarm-is-setting-12-hours-later-in-my-alarm-android-app-whenever-the-time-is-12

**Comment by Bnyro** [comment]
That seems to be it, thank you so much @Neon-44 <3

**Comment by Neon-44** [comment]
always glad to help.
can't wait to replace my default clock app with this on my new AOSP Phone, now that it works :):)

**Comment by PranavPurwar** [comment]
Now, after updating to CI build, the alarm goes off correctly, but there's no sound, only the notification, making it essentially useless for most cases
