### ISSUE TITLE
Gestures YAY or NAY

### ISSUE THREAD

**Issue by nightznero** [you-apps/ClockYou#338]
### Describe your suggested feature

for the love of god add option to disable gestures to delete alarms. I have disabled everywhere possible gestures and can't count how many (almost) delete my alarms cuz of my fat fingers

### Other details

to not make another "request"
Once again asking for manual sorting alarms ε:

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Sorry, such kind of customizations are out of scope. There's a confirmation dialog, do you can't sccidentally delete sth.
