### ISSUE TITLE
Ringtone preview doesn't stop after picking one

### ISSUE THREAD

**Issue by Martysh12** [you-apps/ClockYou#339]
### Steps to reproduce

1. Open a ringtone picker dialogue.
2. Click on one of the ringtone preview buttons.
3. Pick any ringtone, which closes the dialogue.
4. The ringtone preview keeps ringing outside of the dialogue.

### Expected behavior

The ringtone should stop ringing when I exit the ringtone picker dialogue.

### Actual behavior

The ringtone continues ringing.

### Clock You version

7.1

### Android version

Android 13

### Other details

Proposed fix:
https://github.com/you-apps/ClockYou/blob/e6097b1659029d22a4dd9dc16b6ca6fc84639cc2/app/src/main/java/com/bnyro/clock/presentation/features/RingtonePickerDialog.kt#L100-L103
Add `ringingToneModel.stopRinging();` to this block.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SuhasDissa** [comment]
Use the latest version of the app (8.0)

**Comment by Martysh12** [comment]
You're right, this bug doesn't happen in ClockYou 8.0.
The latest version of ClockYou on F-Droid is 7.1, so I assumed it is the latest version. Closing this issue.
