### ISSUE TITLE
Transparent background for the clock widget

### ISSUE THREAD

**Issue by Maell1** [you-apps/ClockYou#344]
### Describe your suggested feature

Hello,
Add new widget with transparent background for the clock please.

Thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please contribute it yourself if you want to have it, the necessary instuctions can be found / asked for at our Matrix room
