### ISSUE TITLE
Timer feature stuck/crashed

### ISSUE THREAD

**Issue by mon4d** [you-apps/ClockYou#346]
### Steps to reproduce

1. Start app
2. Open timer tab
3. Start timer (iE 1h)
4. Switch or minimize app
5. Go back into app, the timer is now frozen; stop and pause buttons dont react
6. Force close and reopen app
7. Timer doesnt exist anymore
8. The timer notification persists but starts counting negatively when finished

### Expected behavior

- Timer should keep going when minimizing app
- Timer should ring when finished

### Actual behavior

- Timer seems to stop existing at all when app goes into background

### Clock You version

8.0

### Android version

Android 14 (GrapheneOS)

### Other details

- Allow background usage is active

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by cmjoz** [comment]
I agree. Use the timer feature a lot and can confirm this bug.

**Comment by SuhasDissa** [comment]
#354
