### ISSUE TITLE
Schedule Alarms by date

### ISSUE THREAD

**Issue by friosrhy** [you-apps/ClockYou#355]
### Describe your suggested feature

Able to set dates for alarms to work through, e.g. 21st may to 30th may to stop alarms for a holiday.
It would work with a calendar popup next to days of the week to let you select, default behaviour would be off.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's out of scope for the app, please use the reminders feature of your calendar app for that or just manually enable / disable the alarm when you need it.
