### ISSUE TITLE
Alarm still ringing after dismiss its notification

### ISSUE THREAD

**Issue by brenard** [you-apps/ClockYou#357]
### Steps to reproduce

1. Configure an alarm
2. Let it trigger, screen lock
3. Unlock your phone and go to notifications list
4. Swipe the alarm notification

### Expected behavior

With my previous phone, when I swipe the notification of an alarm, it's snooze it or it's stop it (configurable behavior)

### Actual behavior

The alarm is still ringing and their is no way to stop it (must restart phone) 

### Clock You version

8.0 (16)

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
https://github.com/you-apps/ClockYou/commit/14df4bc14da87b9beb16efe0ebea7dd9a7f95dfe
