### ISSUE TITLE
Allow to snooze an alarm by using volume buttons

### ISSUE THREAD

**Issue by brenard** [you-apps/ClockYou#358]
### Describe your suggested feature

When an alarm is ringing, it would be great if we could snooze it by pushing any of volumes buttons.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
From my research, it unfortunately seems like we can't detect key events from services reliably, which makes this feature impossible.

The only way would be to register a `MediaSession`, and that'd be a very hackish work around and not the way media sessions are supposed to be used.
