### ISSUE TITLE
Timer not ringing after the phone locks

### ISSUE THREAD

**Issue by markbara-git** [you-apps/ClockYou#359]
### Steps to reproduce

1. Set timer for 15:00 minutes
2. Go back to home and leave the phone unattended
3. After 15:00 the phone don't ring
4. The notification bubble keeps counting backwards and you have to force stop the app to make it disappear. 
Tested On Motorola Edge 50 Pro with disabled power saver and with app full access to the battery.

### Expected behavior

The timer should ring even when the phone is locked.

### Actual behavior

The phone not ringing after the timer reached 0:00, instead the notification bubble starts counting backwards and you have to force stop the app.

### Clock You version

8.0 from F-Droid

### Android version

Android 14

### Other details

![Screenshot_20240723-123938_Microsoft Launcher](https://github.com/user-attachments/assets/f23b0255-b398-4f23-b3d1-72688fc5a61d)
![Screenshot_20240723-123957_Clock You](https://github.com/user-attachments/assets/c295ebb3-63ad-4a6f-9bd6-a181d9c7e1d3)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by czarnyckm** [comment]
Maybe missing permission
 `<uses-permission android:name="android.permission.FOREGROUND_SERVICE_SPECIAL_USE" />`

**Comment by flux77** [comment]
@czarnyckm That permission exists: https://github.com/you-apps/ClockYou/blob/v8.0/app/src/main/AndroidManifest.xml#L9

https://github.com/you-apps/ClockYou/blob/e6097b1659029d22a4dd9dc16b6ca6fc84639cc2/app/src/main/AndroidManifest.xml#L9

**Comment by flux77** [comment]
I am also experiencing this issue in Clock You version 8.0 (from F-Droid). My device is Samsung Galaxy A15 running Android 14. 

In addition to this issue with the timer, when the screen is locked, the alarm clock does not ring or end up ringing long after the time that I have set. I wonder if that alarm clock problem could be related to this timer issue. @markbara-git Do you have similar issues with your alarms?

**Comment by flux77** [comment]
It might be instructive to compare the permissions in Clock You's app manifest against another open source Android alarm clock app such as Fossify Clock, which rings its timers and alarms as expected on my device (Samsung Galaxy A15 running Android 14).

Compare:
* https://github.com/you-apps/ClockYou/blob/v8.0/app/src/main/AndroidManifest.xml#L5-L12
* https://github.com/FossifyOrg/Clock/blob/1.0.0/app/src/main/AndroidManifest.xml#L5-L17

**Comment by czarnyckm** [comment]
I use previous clock you version 7.1 without any issues with Android 14

**Comment by markbara-git** [comment]
@flux77 It seems that in my case the alarm works properly. The problem is with the timer.

**Comment by porkmanager** [comment]
I have the same issue with 8.0 from F-Droid. And sometimes the timer is hanging while it runs

**Comment by Bnyro** [comment]
https://github.com/you-apps/ClockYou/commit/dc40e6178639524cfb305d27890850dff9aed1ae

**Comment by Bnyro** [comment]
Android automatically killed the timer service when the screen is off and thus also the corresponding notification - the finished notification is now independent of the service (different ID)
