### ISSUE TITLE
[Feature request] delete alarm after dismissed as a default option 

### ISSUE THREAD

**Issue by HusniMuhammad** [you-apps/ClockYou#362]
**Feature request**

`delete alarm after dismissed` option in settings section of this app to set as default

**Comment by Bnyro** [comment]
Sorry, I fail to see a good reason why you can't just manually delete the alarm.

**Comment by HusniMuhammad** [comment]
> Sorry, I fail to see a good reason why you can't just manually delete the alarm.

Ok I found the solution that the alarm label should not be empty 

![Screenshot_20240922-174254](https://github.com/user-attachments/assets/3a566b3b-4a5a-4559-85a3-e82ad8404679)
