### ISSUE TITLE
Publish app on a secure app store.

### ISSUE THREAD

**Issue by graphene1over** [you-apps/ClockYou#365]
### Describe your suggested feature

Currently the only way to obtain the app is through sideloading or fdroid. This is a security risk due to being unable to verify the legitimacy of the app and [fdroid's major security flaws](https://privsec.dev/posts/android/f-droid-security-issues/).

Currently there are two secure app stores, [Accrescent](https://accrescent.app/), which is currently in whitelist-only alpha and Gplay, both of which employ certificate pinning and verify the downloads to mitigate MITM attacks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by graphene1over** [comment]
Alternatively publishing the signing certificate hash separately to distrust the site would be an option, which would make it possible to use [AppVerifier](https://github.com/soupslurpr/AppVerifier) to verify the app's legitimacy. However this is a suboptimal solution.

**Comment by Bnyro** [comment]
Neither of them is planned due to additional efforts that would be needed. There's currently a lack of time and contributors, and I don't have interest in making the release workflow more complicated.
