### ISSUE TITLE
The timer stopped working

### ISSUE THREAD

**Issue by Notesuree** [you-apps/ClockYou#368]
### Steps to reproduce

1. Start the timer.
2. Exit the application
3. Sign in to the app
4. The timer has stopped and the buttons do not work

### Expected behavior

Keep the timer running

### Actual behavior

The timer stopped as soon as I exited the app

### Clock You version

8.0 (16)

### Android version

Android 12

### Other details

https://github.com/user-attachments/assets/b46c997d-82d4-4cef-8fda-79d3a643dd23

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Already fixed in latest debug.
