### ISSUE TITLE
The Start tab does not change visually

### ISSUE THREAD

**Issue by Notesuree** [you-apps/ClockYou#369]
### Steps to reproduce

1. Go to settings
2. Change the Start tab
3. It doesn't seem to have changed

### Expected behavior

Change button option

### Actual behavior

https://github.com/user-attachments/assets/1d0ffbd2-5253-4865-b083-6bad64fa8995

### Clock You version

8.0 (16)

### Android version

Android 12

### Other details

...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Already fixed in latest debug.
