### ISSUE TITLE
End time on timer 

### ISSUE THREAD

**Issue by Akshaythorat376** [you-apps/ClockYou#372]
### Describe your suggested feature

Please add a estimate of time when a timer ends on timer countdown screen and it should adjust its estimate when I pause or resume timer. If you want to see it in action then you can see it in the stock clock app in one UI on Samsung phones. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
> Please add a estimate of time when a timer ends
>
To make sure I understand you properly, you mean a time as in `7:25` pm? E.g. when you start a 5 minute timer at `7:20`, you want it to show `7:25`?

**Comment by Akshaythorat376** [comment]
No, it should display remaining time as usual, but at the same time in
small size font it should display estimate of ending time. You can see it
in action in samsung clock app if you have access to a Samsung galaxy phone
running recent versions of one UI.

**Comment by Akshaythorat376** [comment]
I will send you a screenshot in few hours. So, you will get a clear idea of
it.
