### ISSUE TITLE
Deleting alarm

### ISSUE THREAD

**Issue by Damglador** [you-apps/ClockYou#373]
### Describe your suggested feature

Simple deleting alarm feature. So user can delete unused alarms to make the list cleaner

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You can swipe to delete.
