### ISSUE TITLE
Incerasing alarm volume

### ISSUE THREAD

**Issue by tomaszk8266** [you-apps/ClockYou#374]
### Describe your suggested feature

An incerasing alarm volume feature, just like in AOSP/Lineage clock. It would be also nice to have an option to vibrate first, and then play alarm sound with incerasing volume.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
had been added in https://github.com/you-apps/ClockYou/commit/d5d39ab89cc744f6ad7f84753866383659f31adf
