### ISSUE TITLE
Too easy to accidentally delete alarms

### ISSUE THREAD

**Issue by shompoe** [you-apps/ClockYou#378]
### Describe your suggested feature

Just swiping an alarm a minute amount without intending to triggers a delete request. I would like it if very short swipes were ignored.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
You're prompted with a confirm dialog, thus I don't see how you could accidentally delete an alarm.
