### ISSUE TITLE
Add options for time settings

### ISSUE THREAD

**Issue by john371911** [you-apps/ClockYou#379]
### Describe your suggested feature

I hope that when setting an alarm or other times, additional options can be added. Users should have the option to invert the scrolling numbers' order so that the numbers above are larger than those below, or implement something like Google Clock, where users can directly drag the clock hands to set the time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's out of scope.
