### ISSUE TITLE
Incorrect time zone offset during daylight savings time

### ISSUE THREAD

**Issue by eclairevoyant** [you-apps/ClockYou#50]
### Steps to reproduce

With system set to New York (currently EDT = UTC-4) and adding a card for Melbourne (which is in Eastern Australia, currently AEST = UTC+10), the Melbourne card is off by an hour. Seems like the app is not accounting for daylight savings time correctly.

I also noticed when I search for New York in the list of time zones, it shows offset as -5.0 (which is incorrect).

### Expected behavior

System time = 21:45
Melbourne card = 11:45 (+1 day)

### Actual behavior

System time = 21:45
Melbourne card = 12:45 (+1 day)

### Clock You version

3.1

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by eclairevoyant** [comment]
You'll have to use something from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
But that doesn't really have anything to do with this issue.

**Comment by Tombstone2K** [comment]
Same issue noticed with London time... Due to British Summer Time, the time in London is UTC +1.....however the app shows UTC +0 for London, which is incorrect
